apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: random-choice
      tier: frontend
  endpoints:
    - port: monitoring
      path: /metrics
      interval: 30s
