apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-prometheus-service.yaml
  - backend-prometheus-servicemonitor.yaml
  - frontend-prometheus-service.yaml
  - frontend-prometheus-servicemonitor.yaml
