apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-backend-service-monitor
  namespace: random-choice
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: random-choice
      tier: backend
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
