prometheus:
  service:
    type: LoadBalancer
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}

grafana:
  adminUser: admin
  adminPassword: password
  service:
    type: LoadBalancer
  defaultDashboardsEnabled: true

alertmanager:
  service:
    type: LoadBalancer
