prometheus:
  service:
    type: ClusterIP
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}

grafana:
  adminUser: admin
  adminPassword: admin123
  service:
    type: ClusterIP
  defaultDashboardsEnabled: true

alertmanager:
  service:
    type: ClusterIP
