apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: random-choice-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/AdhamBasheir/random-choices-devops.git'
    targetRevision: HEAD
    path: k8s/apps
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: random-choice
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      