server:
  service:
    type: LoadBalancer
configs:
  secret:
    argocdServerAdminPassword: "$2a$10$LVspxIzpEtM3dEVR/Fx33uSgKfFGhah.QxiPLFKqvbaIPnSaRI92G" #password
  admin:
    passwordSecret:
      createSecret: false
  cm:
    resource.customizations: |
      batch/Job:
        ignoreDifferences: |
          jsonPointers:
            - /status
  timeout.reconciliation: 30s
