global:
  domain: services.noodleblitz.space

server:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: gateway.k8s.io
    # annotations:
    #   cert-manager.io/cluster-issuer: "letsencrypt"
    hostname: services.noodleblitz.space
    path: /
    pathType: Prefix
    tls:
      - hosts:
          - services.noodleblitz.space
        secretName: noodleblitz-services-tls

configs:
  secret:
    argocdServerAdminPassword: "$2a$10$LVspxIzpEtM3dEVR/Fx33uSgKfFGhah.QxiPLFKqvbaIPnSaRI92G" #password
  admin:
    passwordSecret:
      createSecret: false
  cm:
    resource.customizations: |
      batch/Job:
        ignoreDifferences: |
          jsonPointers:
            - /status
  timeout.reconciliation: 30s
