apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-route
  namespace: argocd
spec:
  parentRefs:
    - name: nginx-gateway
      namespace: nginx-gateway
  hostnames:
    - services.noodleblitz.space
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /argocd
      filters:
        - type: URLRewrite
          # hostname: argocd.example.com
          urlRewrite:
            path:
              type: ReplaceFullPath
              replaceFullPath: /
              # replaceFullPath: /applications
        # - type: RequestRedirect
        #   requestRedirect:
        #     scheme: HTTPS
        #     host: argocd.example.com
        #     port: 443
        #     statusCode: 301
      backendRefs:
        - name: argocd-server
          port: 80
