apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/nginx/nginx-gateway-fabric/config/crd/gateway-api/standard?ref=v2.0.0
  - https://raw.githubusercontent.com/nginx/nginx-gateway-fabric/v2.0.0/deploy/crds.yaml
  - https://raw.githubusercontent.com/nginx/nginx-gateway-fabric/v2.0.0/deploy/default/deploy.yaml
  - noodleblitz-root-secret.yaml
  - noodleblitz-services-secret.yaml
  - gateway.yaml
  - backend-route.yaml
  - frontend-route.yaml
  # - argocd-route.yaml
  # - prometheus-route.yaml
  # - grafana-route.yaml
  # - alertmanager-route.yaml
  # - jenkins-route.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/kubernetes/service/loadBalancerIP
        value: 104.198.170.9
    target:
      kind: NginxProxy
      name: nginx-gateway-proxy-config
      namespace: nginx-gateway
  - patch: |-
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/hook: PostSync
          argocd.argoproj.io/hook-delete-policy: HookSucceeded
    target:
      kind: Job
      name: nginx-gateway-cert-generator
      namespace: nginx-gateway
