name: Backend Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - uses: actions/checkout@v4
    - name: Build and Push the Docker image
      working-directory: ./backend
      run: |
        docker build --file Dockerfile --tag random-choice-devops-backend .
        docker tag random-choice-devops-backend adhambasheir/random-choice-devops-backend:latest
        docker push adhambasheir/random-choice-devops-backend:latest
