name: Frontend Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'frontend/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - uses: actions/checkout@v4
    - name: Build and Push the Docker image
      working-directory: ./frontend
      run: |
        docker build --file Dockerfile --tag random-choice-devops-frontend .
        docker tag random-choice-devops-frontend adhambasheir/random-choice-devops-frontend:latest
        docker push adhambasheir/random-choice-devops-frontend:latest
