# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Build and Test

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Confirm go.sum exists before caching
      run: ls -l backend/go.sum

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "${{ vars.GO_VERSION }}"
    
    - name: Debug repo structure
      run: |
        echo "Repo root contents:"
        ls -R .
    
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ vars.GO_VERSION }}-${{ hashFiles('backend/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ vars.GO_VERSION }}-
          ${{ runner.os }}-go-
          ${{ runner.os }}-

    - name: Build
      working-directory: ./backend
      run: go build -v ./...

    - name: Test
      working-directory: ./backend
      run: go test -v ./...
